class ApiResources:
    GetListUsers = 'api/users?page=2'
    Get_Single_User = 'api/users/2'
    Get_Single_User_NotFound = 'api/users/23'
    Get_List_Resource = 'api/unknown'
    Get_Single_Resource = 'api/unknown/2'
    Get_Single_Resource_NotFound = 'api/unknown/23'
    Post_Create = 'api/users'
    Put_Patch_Update = 'api/users/2'
    Patch_Update = 'api/users/2'
    Delete = 'api/users/2'
    Post_Register = 'api/register'
    Post_Login = 'api/login'
    Get_Delayed_Response = 'api/users?delay=3'